// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientRequest.proto

public final class ClientRequestOuterClass {
  private ClientRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string table = 3;</code>
     */
    boolean hasTable();
    /**
     * <code>optional string table = 3;</code>
     */
    java.lang.String getTable();
    /**
     * <code>optional string table = 3;</code>
     */
    com.google.protobuf.ByteString
        getTableBytes();

    /**
     * <code>optional string key = 4;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 4;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 4;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>repeated string fields = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getFieldsList();
    /**
     * <code>repeated string fields = 5;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated string fields = 5;</code>
     */
    java.lang.String getFields(int index);
    /**
     * <code>repeated string fields = 5;</code>
     */
    com.google.protobuf.ByteString
        getFieldsBytes(int index);

    /**
     * <code>optional string startkey = 6;</code>
     */
    boolean hasStartkey();
    /**
     * <code>optional string startkey = 6;</code>
     */
    java.lang.String getStartkey();
    /**
     * <code>optional string startkey = 6;</code>
     */
    com.google.protobuf.ByteString
        getStartkeyBytes();

    /**
     * <code>optional int32 recordcount = 7;</code>
     */
    boolean hasRecordcount();
    /**
     * <code>optional int32 recordcount = 7;</code>
     */
    int getRecordcount();

    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    java.util.List<ClientRequestOuterClass.FieldValue> 
        getFvList();
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    ClientRequestOuterClass.FieldValue getFv(int index);
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    int getFvCount();
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    java.util.List<? extends ClientRequestOuterClass.FieldValueOrBuilder> 
        getFvOrBuilderList();
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    ClientRequestOuterClass.FieldValueOrBuilder getFvOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ClientRequest}
   */
  public static final class ClientRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientRequest)
      ClientRequestOrBuilder {
    // Use ClientRequest.newBuilder() to construct.
    private ClientRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientRequest defaultInstance;
    public static ClientRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ClientRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              table_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              key_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                fields_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              fields_.add(bs);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              startkey_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              recordcount_ = input.readInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                fv_ = new java.util.ArrayList<ClientRequestOuterClass.FieldValue>();
                mutable_bitField0_ |= 0x00000080;
              }
              fv_.add(input.readMessage(ClientRequestOuterClass.FieldValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          fields_ = fields_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          fv_ = java.util.Collections.unmodifiableList(fv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRequestOuterClass.internal_static_ClientRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRequestOuterClass.internal_static_ClientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRequestOuterClass.ClientRequest.class, ClientRequestOuterClass.ClientRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientRequest> PARSER =
        new com.google.protobuf.AbstractParser<ClientRequest>() {
      public ClientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_FIELD_NUMBER = 3;
    private java.lang.Object table_;
    /**
     * <code>optional string table = 3;</code>
     */
    public boolean hasTable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string table = 3;</code>
     */
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          table_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string table = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 4;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 4;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string key = 4;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 4;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList fields_;
    /**
     * <code>repeated string fields = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated string fields = 5;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated string fields = 5;</code>
     */
    public java.lang.String getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated string fields = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFieldsBytes(int index) {
      return fields_.getByteString(index);
    }

    public static final int STARTKEY_FIELD_NUMBER = 6;
    private java.lang.Object startkey_;
    /**
     * <code>optional string startkey = 6;</code>
     */
    public boolean hasStartkey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string startkey = 6;</code>
     */
    public java.lang.String getStartkey() {
      java.lang.Object ref = startkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string startkey = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStartkeyBytes() {
      java.lang.Object ref = startkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDCOUNT_FIELD_NUMBER = 7;
    private int recordcount_;
    /**
     * <code>optional int32 recordcount = 7;</code>
     */
    public boolean hasRecordcount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 recordcount = 7;</code>
     */
    public int getRecordcount() {
      return recordcount_;
    }

    public static final int FV_FIELD_NUMBER = 8;
    private java.util.List<ClientRequestOuterClass.FieldValue> fv_;
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    public java.util.List<ClientRequestOuterClass.FieldValue> getFvList() {
      return fv_;
    }
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    public java.util.List<? extends ClientRequestOuterClass.FieldValueOrBuilder> 
        getFvOrBuilderList() {
      return fv_;
    }
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    public int getFvCount() {
      return fv_.size();
    }
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    public ClientRequestOuterClass.FieldValue getFv(int index) {
      return fv_.get(index);
    }
    /**
     * <code>repeated .FieldValue fv = 8;</code>
     */
    public ClientRequestOuterClass.FieldValueOrBuilder getFvOrBuilder(
        int index) {
      return fv_.get(index);
    }

    private void initFields() {
      id_ = "";
      type_ = "";
      table_ = "";
      key_ = "";
      fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      startkey_ = "";
      recordcount_ = 0;
      fv_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFvCount(); i++) {
        if (!getFv(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTableBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getKeyBytes());
      }
      for (int i = 0; i < fields_.size(); i++) {
        output.writeBytes(5, fields_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getStartkeyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, recordcount_);
      }
      for (int i = 0; i < fv_.size(); i++) {
        output.writeMessage(8, fv_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTableBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fields_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldsList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStartkeyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, recordcount_);
      }
      for (int i = 0; i < fv_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, fv_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientRequestOuterClass.ClientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientRequestOuterClass.ClientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRequestOuterClass.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientRequestOuterClass.ClientRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientRequest)
        ClientRequestOuterClass.ClientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRequestOuterClass.internal_static_ClientRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRequestOuterClass.internal_static_ClientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRequestOuterClass.ClientRequest.class, ClientRequestOuterClass.ClientRequest.Builder.class);
      }

      // Construct using ClientRequestOuterClass.ClientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFvFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        table_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        startkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        recordcount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (fvBuilder_ == null) {
          fv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          fvBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRequestOuterClass.internal_static_ClientRequest_descriptor;
      }

      public ClientRequestOuterClass.ClientRequest getDefaultInstanceForType() {
        return ClientRequestOuterClass.ClientRequest.getDefaultInstance();
      }

      public ClientRequestOuterClass.ClientRequest build() {
        ClientRequestOuterClass.ClientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientRequestOuterClass.ClientRequest buildPartial() {
        ClientRequestOuterClass.ClientRequest result = new ClientRequestOuterClass.ClientRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.table_ = table_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.key_ = key_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          fields_ = fields_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.fields_ = fields_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startkey_ = startkey_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.recordcount_ = recordcount_;
        if (fvBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            fv_ = java.util.Collections.unmodifiableList(fv_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.fv_ = fv_;
        } else {
          result.fv_ = fvBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientRequestOuterClass.ClientRequest) {
          return mergeFrom((ClientRequestOuterClass.ClientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientRequestOuterClass.ClientRequest other) {
        if (other == ClientRequestOuterClass.ClientRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasTable()) {
          bitField0_ |= 0x00000004;
          table_ = other.table_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000008;
          key_ = other.key_;
          onChanged();
        }
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
        if (other.hasStartkey()) {
          bitField0_ |= 0x00000020;
          startkey_ = other.startkey_;
          onChanged();
        }
        if (other.hasRecordcount()) {
          setRecordcount(other.getRecordcount());
        }
        if (fvBuilder_ == null) {
          if (!other.fv_.isEmpty()) {
            if (fv_.isEmpty()) {
              fv_ = other.fv_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureFvIsMutable();
              fv_.addAll(other.fv_);
            }
            onChanged();
          }
        } else {
          if (!other.fv_.isEmpty()) {
            if (fvBuilder_.isEmpty()) {
              fvBuilder_.dispose();
              fvBuilder_ = null;
              fv_ = other.fv_;
              bitField0_ = (bitField0_ & ~0x00000080);
              fvBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFvFieldBuilder() : null;
            } else {
              fvBuilder_.addAllMessages(other.fv_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getFvCount(); i++) {
          if (!getFv(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientRequestOuterClass.ClientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientRequestOuterClass.ClientRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object table_ = "";
      /**
       * <code>optional string table = 3;</code>
       */
      public boolean hasTable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string table = 3;</code>
       */
      public java.lang.String getTable() {
        java.lang.Object ref = table_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            table_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string table = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTableBytes() {
        java.lang.Object ref = table_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          table_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string table = 3;</code>
       */
      public Builder setTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        table_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string table = 3;</code>
       */
      public Builder clearTable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        table_ = getDefaultInstance().getTable();
        onChanged();
        return this;
      }
      /**
       * <code>optional string table = 3;</code>
       */
      public Builder setTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        table_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 4;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 4;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          fields_ = new com.google.protobuf.LazyStringArrayList(fields_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldsList() {
        return fields_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public int getFieldsCount() {
        return fields_.size();
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public java.lang.String getFields(int index) {
        return fields_.get(index);
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFieldsBytes(int index) {
        return fields_.getByteString(index);
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public Builder setFields(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public Builder addFields(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public Builder clearFields() {
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 5;</code>
       */
      public Builder addFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object startkey_ = "";
      /**
       * <code>optional string startkey = 6;</code>
       */
      public boolean hasStartkey() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string startkey = 6;</code>
       */
      public java.lang.String getStartkey() {
        java.lang.Object ref = startkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            startkey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string startkey = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStartkeyBytes() {
        java.lang.Object ref = startkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string startkey = 6;</code>
       */
      public Builder setStartkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        startkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string startkey = 6;</code>
       */
      public Builder clearStartkey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startkey_ = getDefaultInstance().getStartkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string startkey = 6;</code>
       */
      public Builder setStartkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        startkey_ = value;
        onChanged();
        return this;
      }

      private int recordcount_ ;
      /**
       * <code>optional int32 recordcount = 7;</code>
       */
      public boolean hasRecordcount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 recordcount = 7;</code>
       */
      public int getRecordcount() {
        return recordcount_;
      }
      /**
       * <code>optional int32 recordcount = 7;</code>
       */
      public Builder setRecordcount(int value) {
        bitField0_ |= 0x00000040;
        recordcount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 recordcount = 7;</code>
       */
      public Builder clearRecordcount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        recordcount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ClientRequestOuterClass.FieldValue> fv_ =
        java.util.Collections.emptyList();
      private void ensureFvIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          fv_ = new java.util.ArrayList<ClientRequestOuterClass.FieldValue>(fv_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ClientRequestOuterClass.FieldValue, ClientRequestOuterClass.FieldValue.Builder, ClientRequestOuterClass.FieldValueOrBuilder> fvBuilder_;

      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public java.util.List<ClientRequestOuterClass.FieldValue> getFvList() {
        if (fvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fv_);
        } else {
          return fvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public int getFvCount() {
        if (fvBuilder_ == null) {
          return fv_.size();
        } else {
          return fvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public ClientRequestOuterClass.FieldValue getFv(int index) {
        if (fvBuilder_ == null) {
          return fv_.get(index);
        } else {
          return fvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder setFv(
          int index, ClientRequestOuterClass.FieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFvIsMutable();
          fv_.set(index, value);
          onChanged();
        } else {
          fvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder setFv(
          int index, ClientRequestOuterClass.FieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.set(index, builderForValue.build());
          onChanged();
        } else {
          fvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder addFv(ClientRequestOuterClass.FieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFvIsMutable();
          fv_.add(value);
          onChanged();
        } else {
          fvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder addFv(
          int index, ClientRequestOuterClass.FieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFvIsMutable();
          fv_.add(index, value);
          onChanged();
        } else {
          fvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder addFv(
          ClientRequestOuterClass.FieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.add(builderForValue.build());
          onChanged();
        } else {
          fvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder addFv(
          int index, ClientRequestOuterClass.FieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.add(index, builderForValue.build());
          onChanged();
        } else {
          fvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder addAllFv(
          java.lang.Iterable<? extends ClientRequestOuterClass.FieldValue> values) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fv_);
          onChanged();
        } else {
          fvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder clearFv() {
        if (fvBuilder_ == null) {
          fv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          fvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public Builder removeFv(int index) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.remove(index);
          onChanged();
        } else {
          fvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public ClientRequestOuterClass.FieldValue.Builder getFvBuilder(
          int index) {
        return getFvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public ClientRequestOuterClass.FieldValueOrBuilder getFvOrBuilder(
          int index) {
        if (fvBuilder_ == null) {
          return fv_.get(index);  } else {
          return fvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public java.util.List<? extends ClientRequestOuterClass.FieldValueOrBuilder> 
           getFvOrBuilderList() {
        if (fvBuilder_ != null) {
          return fvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fv_);
        }
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public ClientRequestOuterClass.FieldValue.Builder addFvBuilder() {
        return getFvFieldBuilder().addBuilder(
            ClientRequestOuterClass.FieldValue.getDefaultInstance());
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public ClientRequestOuterClass.FieldValue.Builder addFvBuilder(
          int index) {
        return getFvFieldBuilder().addBuilder(
            index, ClientRequestOuterClass.FieldValue.getDefaultInstance());
      }
      /**
       * <code>repeated .FieldValue fv = 8;</code>
       */
      public java.util.List<ClientRequestOuterClass.FieldValue.Builder> 
           getFvBuilderList() {
        return getFvFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ClientRequestOuterClass.FieldValue, ClientRequestOuterClass.FieldValue.Builder, ClientRequestOuterClass.FieldValueOrBuilder> 
          getFvFieldBuilder() {
        if (fvBuilder_ == null) {
          fvBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ClientRequestOuterClass.FieldValue, ClientRequestOuterClass.FieldValue.Builder, ClientRequestOuterClass.FieldValueOrBuilder>(
                  fv_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          fv_ = null;
        }
        return fvBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ClientRequest)
    }

    static {
      defaultInstance = new ClientRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientRequest)
  }

  public interface FieldValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FieldValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string field = 1;</code>
     */
    boolean hasField();
    /**
     * <code>required string field = 1;</code>
     */
    java.lang.String getField();
    /**
     * <code>required string field = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldBytes();

    /**
     * <code>required bytes value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code FieldValue}
   */
  public static final class FieldValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FieldValue)
      FieldValueOrBuilder {
    // Use FieldValue.newBuilder() to construct.
    private FieldValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FieldValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FieldValue defaultInstance;
    public static FieldValue getDefaultInstance() {
      return defaultInstance;
    }

    public FieldValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FieldValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              field_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRequestOuterClass.internal_static_FieldValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRequestOuterClass.internal_static_FieldValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRequestOuterClass.FieldValue.class, ClientRequestOuterClass.FieldValue.Builder.class);
    }

    public static com.google.protobuf.Parser<FieldValue> PARSER =
        new com.google.protobuf.AbstractParser<FieldValue>() {
      public FieldValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FieldValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FieldValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIELD_FIELD_NUMBER = 1;
    private java.lang.Object field_;
    /**
     * <code>required string field = 1;</code>
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string field = 1;</code>
     */
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          field_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      field_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasField()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFieldBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFieldBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientRequestOuterClass.FieldValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientRequestOuterClass.FieldValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientRequestOuterClass.FieldValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRequestOuterClass.FieldValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientRequestOuterClass.FieldValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FieldValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FieldValue)
        ClientRequestOuterClass.FieldValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRequestOuterClass.internal_static_FieldValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRequestOuterClass.internal_static_FieldValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRequestOuterClass.FieldValue.class, ClientRequestOuterClass.FieldValue.Builder.class);
      }

      // Construct using ClientRequestOuterClass.FieldValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        field_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRequestOuterClass.internal_static_FieldValue_descriptor;
      }

      public ClientRequestOuterClass.FieldValue getDefaultInstanceForType() {
        return ClientRequestOuterClass.FieldValue.getDefaultInstance();
      }

      public ClientRequestOuterClass.FieldValue build() {
        ClientRequestOuterClass.FieldValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientRequestOuterClass.FieldValue buildPartial() {
        ClientRequestOuterClass.FieldValue result = new ClientRequestOuterClass.FieldValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.field_ = field_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientRequestOuterClass.FieldValue) {
          return mergeFrom((ClientRequestOuterClass.FieldValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientRequestOuterClass.FieldValue other) {
        if (other == ClientRequestOuterClass.FieldValue.getDefaultInstance()) return this;
        if (other.hasField()) {
          bitField0_ |= 0x00000001;
          field_ = other.field_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasField()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientRequestOuterClass.FieldValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientRequestOuterClass.FieldValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object field_ = "";
      /**
       * <code>required string field = 1;</code>
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string field = 1;</code>
       */
      public java.lang.String getField() {
        java.lang.Object ref = field_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            field_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        java.lang.Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string field = 1;</code>
       */
      public Builder setField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string field = 1;</code>
       */
      public Builder clearField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <code>required string field = 1;</code>
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FieldValue)
    }

    static {
      defaultInstance = new FieldValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FieldValue)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FieldValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientRequest.proto\"\225\001\n\rClientRequest\022" +
      "\n\n\002id\030\001 \002(\t\022\014\n\004type\030\002 \002(\t\022\r\n\005table\030\003 \001(\t" +
      "\022\013\n\003key\030\004 \001(\t\022\016\n\006fields\030\005 \003(\t\022\020\n\010startke" +
      "y\030\006 \001(\t\022\023\n\013recordcount\030\007 \001(\005\022\027\n\002fv\030\010 \003(\013" +
      "2\013.FieldValue\"*\n\nFieldValue\022\r\n\005field\030\001 \002" +
      "(\t\022\r\n\005value\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientRequest_descriptor,
        new java.lang.String[] { "Id", "Type", "Table", "Key", "Fields", "Startkey", "Recordcount", "Fv", });
    internal_static_FieldValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FieldValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FieldValue_descriptor,
        new java.lang.String[] { "Field", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
