// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientRespond.proto

public final class ClientRespondOuterClass {
  private ClientRespondOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientRespondOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientRespond)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required string status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>required string status = 3;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>required string status = 3;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>optional .MapFieldValue fv = 4;</code>
     */
    boolean hasFv();
    /**
     * <code>optional .MapFieldValue fv = 4;</code>
     */
    ClientRespondOuterClass.MapFieldValue getFv();
    /**
     * <code>optional .MapFieldValue fv = 4;</code>
     */
    ClientRespondOuterClass.MapFieldValueOrBuilder getFvOrBuilder();

    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    java.util.List<ClientRespondOuterClass.MapFieldValue> 
        getVfvList();
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    ClientRespondOuterClass.MapFieldValue getVfv(int index);
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    int getVfvCount();
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    java.util.List<? extends ClientRespondOuterClass.MapFieldValueOrBuilder> 
        getVfvOrBuilderList();
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    ClientRespondOuterClass.MapFieldValueOrBuilder getVfvOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ClientRespond}
   */
  public static final class ClientRespond extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientRespond)
      ClientRespondOrBuilder {
    // Use ClientRespond.newBuilder() to construct.
    private ClientRespond(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientRespond(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientRespond defaultInstance;
    public static ClientRespond getDefaultInstance() {
      return defaultInstance;
    }

    public ClientRespond getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientRespond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              type_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              status_ = bs;
              break;
            }
            case 34: {
              ClientRespondOuterClass.MapFieldValue.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = fv_.toBuilder();
              }
              fv_ = input.readMessage(ClientRespondOuterClass.MapFieldValue.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fv_);
                fv_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                vfv_ = new java.util.ArrayList<ClientRespondOuterClass.MapFieldValue>();
                mutable_bitField0_ |= 0x00000010;
              }
              vfv_.add(input.readMessage(ClientRespondOuterClass.MapFieldValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          vfv_ = java.util.Collections.unmodifiableList(vfv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRespondOuterClass.internal_static_ClientRespond_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRespondOuterClass.internal_static_ClientRespond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRespondOuterClass.ClientRespond.class, ClientRespondOuterClass.ClientRespond.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientRespond> PARSER =
        new com.google.protobuf.AbstractParser<ClientRespond>() {
      public ClientRespond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientRespond(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRespond> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private java.lang.Object status_;
    /**
     * <code>required string status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string status = 3;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FV_FIELD_NUMBER = 4;
    private ClientRespondOuterClass.MapFieldValue fv_;
    /**
     * <code>optional .MapFieldValue fv = 4;</code>
     */
    public boolean hasFv() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .MapFieldValue fv = 4;</code>
     */
    public ClientRespondOuterClass.MapFieldValue getFv() {
      return fv_;
    }
    /**
     * <code>optional .MapFieldValue fv = 4;</code>
     */
    public ClientRespondOuterClass.MapFieldValueOrBuilder getFvOrBuilder() {
      return fv_;
    }

    public static final int VFV_FIELD_NUMBER = 5;
    private java.util.List<ClientRespondOuterClass.MapFieldValue> vfv_;
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    public java.util.List<ClientRespondOuterClass.MapFieldValue> getVfvList() {
      return vfv_;
    }
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    public java.util.List<? extends ClientRespondOuterClass.MapFieldValueOrBuilder> 
        getVfvOrBuilderList() {
      return vfv_;
    }
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    public int getVfvCount() {
      return vfv_.size();
    }
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    public ClientRespondOuterClass.MapFieldValue getVfv(int index) {
      return vfv_.get(index);
    }
    /**
     * <code>repeated .MapFieldValue Vfv = 5;</code>
     */
    public ClientRespondOuterClass.MapFieldValueOrBuilder getVfvOrBuilder(
        int index) {
      return vfv_.get(index);
    }

    private void initFields() {
      id_ = "";
      type_ = "";
      status_ = "";
      fv_ = ClientRespondOuterClass.MapFieldValue.getDefaultInstance();
      vfv_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFv()) {
        if (!getFv().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getVfvCount(); i++) {
        if (!getVfv(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStatusBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, fv_);
      }
      for (int i = 0; i < vfv_.size(); i++) {
        output.writeMessage(5, vfv_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStatusBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, fv_);
      }
      for (int i = 0; i < vfv_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, vfv_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientRespondOuterClass.ClientRespond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientRespondOuterClass.ClientRespond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientRespondOuterClass.ClientRespond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRespondOuterClass.ClientRespond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientRespondOuterClass.ClientRespond prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientRespond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientRespond)
        ClientRespondOuterClass.ClientRespondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRespondOuterClass.internal_static_ClientRespond_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRespondOuterClass.internal_static_ClientRespond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRespondOuterClass.ClientRespond.class, ClientRespondOuterClass.ClientRespond.Builder.class);
      }

      // Construct using ClientRespondOuterClass.ClientRespond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFvFieldBuilder();
          getVfvFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (fvBuilder_ == null) {
          fv_ = ClientRespondOuterClass.MapFieldValue.getDefaultInstance();
        } else {
          fvBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (vfvBuilder_ == null) {
          vfv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          vfvBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRespondOuterClass.internal_static_ClientRespond_descriptor;
      }

      public ClientRespondOuterClass.ClientRespond getDefaultInstanceForType() {
        return ClientRespondOuterClass.ClientRespond.getDefaultInstance();
      }

      public ClientRespondOuterClass.ClientRespond build() {
        ClientRespondOuterClass.ClientRespond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientRespondOuterClass.ClientRespond buildPartial() {
        ClientRespondOuterClass.ClientRespond result = new ClientRespondOuterClass.ClientRespond(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (fvBuilder_ == null) {
          result.fv_ = fv_;
        } else {
          result.fv_ = fvBuilder_.build();
        }
        if (vfvBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            vfv_ = java.util.Collections.unmodifiableList(vfv_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.vfv_ = vfv_;
        } else {
          result.vfv_ = vfvBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientRespondOuterClass.ClientRespond) {
          return mergeFrom((ClientRespondOuterClass.ClientRespond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientRespondOuterClass.ClientRespond other) {
        if (other == ClientRespondOuterClass.ClientRespond.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasStatus()) {
          bitField0_ |= 0x00000004;
          status_ = other.status_;
          onChanged();
        }
        if (other.hasFv()) {
          mergeFv(other.getFv());
        }
        if (vfvBuilder_ == null) {
          if (!other.vfv_.isEmpty()) {
            if (vfv_.isEmpty()) {
              vfv_ = other.vfv_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureVfvIsMutable();
              vfv_.addAll(other.vfv_);
            }
            onChanged();
          }
        } else {
          if (!other.vfv_.isEmpty()) {
            if (vfvBuilder_.isEmpty()) {
              vfvBuilder_.dispose();
              vfvBuilder_ = null;
              vfv_ = other.vfv_;
              bitField0_ = (bitField0_ & ~0x00000010);
              vfvBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVfvFieldBuilder() : null;
            } else {
              vfvBuilder_.addAllMessages(other.vfv_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (hasFv()) {
          if (!getFv().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getVfvCount(); i++) {
          if (!getVfv(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientRespondOuterClass.ClientRespond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientRespondOuterClass.ClientRespond) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>required string status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string status = 3;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string status = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string status = 3;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 3;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 3;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }

      private ClientRespondOuterClass.MapFieldValue fv_ = ClientRespondOuterClass.MapFieldValue.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ClientRespondOuterClass.MapFieldValue, ClientRespondOuterClass.MapFieldValue.Builder, ClientRespondOuterClass.MapFieldValueOrBuilder> fvBuilder_;
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public boolean hasFv() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public ClientRespondOuterClass.MapFieldValue getFv() {
        if (fvBuilder_ == null) {
          return fv_;
        } else {
          return fvBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public Builder setFv(ClientRespondOuterClass.MapFieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fv_ = value;
          onChanged();
        } else {
          fvBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public Builder setFv(
          ClientRespondOuterClass.MapFieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          fv_ = builderForValue.build();
          onChanged();
        } else {
          fvBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public Builder mergeFv(ClientRespondOuterClass.MapFieldValue value) {
        if (fvBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              fv_ != ClientRespondOuterClass.MapFieldValue.getDefaultInstance()) {
            fv_ =
              ClientRespondOuterClass.MapFieldValue.newBuilder(fv_).mergeFrom(value).buildPartial();
          } else {
            fv_ = value;
          }
          onChanged();
        } else {
          fvBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public Builder clearFv() {
        if (fvBuilder_ == null) {
          fv_ = ClientRespondOuterClass.MapFieldValue.getDefaultInstance();
          onChanged();
        } else {
          fvBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public ClientRespondOuterClass.MapFieldValue.Builder getFvBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getFvFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      public ClientRespondOuterClass.MapFieldValueOrBuilder getFvOrBuilder() {
        if (fvBuilder_ != null) {
          return fvBuilder_.getMessageOrBuilder();
        } else {
          return fv_;
        }
      }
      /**
       * <code>optional .MapFieldValue fv = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ClientRespondOuterClass.MapFieldValue, ClientRespondOuterClass.MapFieldValue.Builder, ClientRespondOuterClass.MapFieldValueOrBuilder> 
          getFvFieldBuilder() {
        if (fvBuilder_ == null) {
          fvBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ClientRespondOuterClass.MapFieldValue, ClientRespondOuterClass.MapFieldValue.Builder, ClientRespondOuterClass.MapFieldValueOrBuilder>(
                  getFv(),
                  getParentForChildren(),
                  isClean());
          fv_ = null;
        }
        return fvBuilder_;
      }

      private java.util.List<ClientRespondOuterClass.MapFieldValue> vfv_ =
        java.util.Collections.emptyList();
      private void ensureVfvIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          vfv_ = new java.util.ArrayList<ClientRespondOuterClass.MapFieldValue>(vfv_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ClientRespondOuterClass.MapFieldValue, ClientRespondOuterClass.MapFieldValue.Builder, ClientRespondOuterClass.MapFieldValueOrBuilder> vfvBuilder_;

      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public java.util.List<ClientRespondOuterClass.MapFieldValue> getVfvList() {
        if (vfvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vfv_);
        } else {
          return vfvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public int getVfvCount() {
        if (vfvBuilder_ == null) {
          return vfv_.size();
        } else {
          return vfvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public ClientRespondOuterClass.MapFieldValue getVfv(int index) {
        if (vfvBuilder_ == null) {
          return vfv_.get(index);
        } else {
          return vfvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder setVfv(
          int index, ClientRespondOuterClass.MapFieldValue value) {
        if (vfvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVfvIsMutable();
          vfv_.set(index, value);
          onChanged();
        } else {
          vfvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder setVfv(
          int index, ClientRespondOuterClass.MapFieldValue.Builder builderForValue) {
        if (vfvBuilder_ == null) {
          ensureVfvIsMutable();
          vfv_.set(index, builderForValue.build());
          onChanged();
        } else {
          vfvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder addVfv(ClientRespondOuterClass.MapFieldValue value) {
        if (vfvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVfvIsMutable();
          vfv_.add(value);
          onChanged();
        } else {
          vfvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder addVfv(
          int index, ClientRespondOuterClass.MapFieldValue value) {
        if (vfvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVfvIsMutable();
          vfv_.add(index, value);
          onChanged();
        } else {
          vfvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder addVfv(
          ClientRespondOuterClass.MapFieldValue.Builder builderForValue) {
        if (vfvBuilder_ == null) {
          ensureVfvIsMutable();
          vfv_.add(builderForValue.build());
          onChanged();
        } else {
          vfvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder addVfv(
          int index, ClientRespondOuterClass.MapFieldValue.Builder builderForValue) {
        if (vfvBuilder_ == null) {
          ensureVfvIsMutable();
          vfv_.add(index, builderForValue.build());
          onChanged();
        } else {
          vfvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder addAllVfv(
          java.lang.Iterable<? extends ClientRespondOuterClass.MapFieldValue> values) {
        if (vfvBuilder_ == null) {
          ensureVfvIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vfv_);
          onChanged();
        } else {
          vfvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder clearVfv() {
        if (vfvBuilder_ == null) {
          vfv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          vfvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public Builder removeVfv(int index) {
        if (vfvBuilder_ == null) {
          ensureVfvIsMutable();
          vfv_.remove(index);
          onChanged();
        } else {
          vfvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public ClientRespondOuterClass.MapFieldValue.Builder getVfvBuilder(
          int index) {
        return getVfvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public ClientRespondOuterClass.MapFieldValueOrBuilder getVfvOrBuilder(
          int index) {
        if (vfvBuilder_ == null) {
          return vfv_.get(index);  } else {
          return vfvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public java.util.List<? extends ClientRespondOuterClass.MapFieldValueOrBuilder> 
           getVfvOrBuilderList() {
        if (vfvBuilder_ != null) {
          return vfvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vfv_);
        }
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public ClientRespondOuterClass.MapFieldValue.Builder addVfvBuilder() {
        return getVfvFieldBuilder().addBuilder(
            ClientRespondOuterClass.MapFieldValue.getDefaultInstance());
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public ClientRespondOuterClass.MapFieldValue.Builder addVfvBuilder(
          int index) {
        return getVfvFieldBuilder().addBuilder(
            index, ClientRespondOuterClass.MapFieldValue.getDefaultInstance());
      }
      /**
       * <code>repeated .MapFieldValue Vfv = 5;</code>
       */
      public java.util.List<ClientRespondOuterClass.MapFieldValue.Builder> 
           getVfvBuilderList() {
        return getVfvFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ClientRespondOuterClass.MapFieldValue, ClientRespondOuterClass.MapFieldValue.Builder, ClientRespondOuterClass.MapFieldValueOrBuilder> 
          getVfvFieldBuilder() {
        if (vfvBuilder_ == null) {
          vfvBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ClientRespondOuterClass.MapFieldValue, ClientRespondOuterClass.MapFieldValue.Builder, ClientRespondOuterClass.MapFieldValueOrBuilder>(
                  vfv_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          vfv_ = null;
        }
        return vfvBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ClientRespond)
    }

    static {
      defaultInstance = new ClientRespond(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientRespond)
  }

  public interface MapFieldValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapFieldValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    java.util.List<ClientRespondOuterClass.FieldValue> 
        getFvList();
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    ClientRespondOuterClass.FieldValue getFv(int index);
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    int getFvCount();
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    java.util.List<? extends ClientRespondOuterClass.FieldValueOrBuilder> 
        getFvOrBuilderList();
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    ClientRespondOuterClass.FieldValueOrBuilder getFvOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MapFieldValue}
   */
  public static final class MapFieldValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MapFieldValue)
      MapFieldValueOrBuilder {
    // Use MapFieldValue.newBuilder() to construct.
    private MapFieldValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapFieldValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapFieldValue defaultInstance;
    public static MapFieldValue getDefaultInstance() {
      return defaultInstance;
    }

    public MapFieldValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapFieldValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                fv_ = new java.util.ArrayList<ClientRespondOuterClass.FieldValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              fv_.add(input.readMessage(ClientRespondOuterClass.FieldValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          fv_ = java.util.Collections.unmodifiableList(fv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRespondOuterClass.internal_static_MapFieldValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRespondOuterClass.internal_static_MapFieldValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRespondOuterClass.MapFieldValue.class, ClientRespondOuterClass.MapFieldValue.Builder.class);
    }

    public static com.google.protobuf.Parser<MapFieldValue> PARSER =
        new com.google.protobuf.AbstractParser<MapFieldValue>() {
      public MapFieldValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapFieldValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapFieldValue> getParserForType() {
      return PARSER;
    }

    public static final int FV_FIELD_NUMBER = 1;
    private java.util.List<ClientRespondOuterClass.FieldValue> fv_;
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    public java.util.List<ClientRespondOuterClass.FieldValue> getFvList() {
      return fv_;
    }
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    public java.util.List<? extends ClientRespondOuterClass.FieldValueOrBuilder> 
        getFvOrBuilderList() {
      return fv_;
    }
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    public int getFvCount() {
      return fv_.size();
    }
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    public ClientRespondOuterClass.FieldValue getFv(int index) {
      return fv_.get(index);
    }
    /**
     * <code>repeated .FieldValue fv = 1;</code>
     */
    public ClientRespondOuterClass.FieldValueOrBuilder getFvOrBuilder(
        int index) {
      return fv_.get(index);
    }

    private void initFields() {
      fv_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getFvCount(); i++) {
        if (!getFv(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < fv_.size(); i++) {
        output.writeMessage(1, fv_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < fv_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fv_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientRespondOuterClass.MapFieldValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientRespondOuterClass.MapFieldValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientRespondOuterClass.MapFieldValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRespondOuterClass.MapFieldValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientRespondOuterClass.MapFieldValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapFieldValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapFieldValue)
        ClientRespondOuterClass.MapFieldValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRespondOuterClass.internal_static_MapFieldValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRespondOuterClass.internal_static_MapFieldValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRespondOuterClass.MapFieldValue.class, ClientRespondOuterClass.MapFieldValue.Builder.class);
      }

      // Construct using ClientRespondOuterClass.MapFieldValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFvFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (fvBuilder_ == null) {
          fv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fvBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRespondOuterClass.internal_static_MapFieldValue_descriptor;
      }

      public ClientRespondOuterClass.MapFieldValue getDefaultInstanceForType() {
        return ClientRespondOuterClass.MapFieldValue.getDefaultInstance();
      }

      public ClientRespondOuterClass.MapFieldValue build() {
        ClientRespondOuterClass.MapFieldValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientRespondOuterClass.MapFieldValue buildPartial() {
        ClientRespondOuterClass.MapFieldValue result = new ClientRespondOuterClass.MapFieldValue(this);
        int from_bitField0_ = bitField0_;
        if (fvBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            fv_ = java.util.Collections.unmodifiableList(fv_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fv_ = fv_;
        } else {
          result.fv_ = fvBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientRespondOuterClass.MapFieldValue) {
          return mergeFrom((ClientRespondOuterClass.MapFieldValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientRespondOuterClass.MapFieldValue other) {
        if (other == ClientRespondOuterClass.MapFieldValue.getDefaultInstance()) return this;
        if (fvBuilder_ == null) {
          if (!other.fv_.isEmpty()) {
            if (fv_.isEmpty()) {
              fv_ = other.fv_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFvIsMutable();
              fv_.addAll(other.fv_);
            }
            onChanged();
          }
        } else {
          if (!other.fv_.isEmpty()) {
            if (fvBuilder_.isEmpty()) {
              fvBuilder_.dispose();
              fvBuilder_ = null;
              fv_ = other.fv_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fvBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFvFieldBuilder() : null;
            } else {
              fvBuilder_.addAllMessages(other.fv_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFvCount(); i++) {
          if (!getFv(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientRespondOuterClass.MapFieldValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientRespondOuterClass.MapFieldValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ClientRespondOuterClass.FieldValue> fv_ =
        java.util.Collections.emptyList();
      private void ensureFvIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          fv_ = new java.util.ArrayList<ClientRespondOuterClass.FieldValue>(fv_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ClientRespondOuterClass.FieldValue, ClientRespondOuterClass.FieldValue.Builder, ClientRespondOuterClass.FieldValueOrBuilder> fvBuilder_;

      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public java.util.List<ClientRespondOuterClass.FieldValue> getFvList() {
        if (fvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fv_);
        } else {
          return fvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public int getFvCount() {
        if (fvBuilder_ == null) {
          return fv_.size();
        } else {
          return fvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public ClientRespondOuterClass.FieldValue getFv(int index) {
        if (fvBuilder_ == null) {
          return fv_.get(index);
        } else {
          return fvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder setFv(
          int index, ClientRespondOuterClass.FieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFvIsMutable();
          fv_.set(index, value);
          onChanged();
        } else {
          fvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder setFv(
          int index, ClientRespondOuterClass.FieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.set(index, builderForValue.build());
          onChanged();
        } else {
          fvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder addFv(ClientRespondOuterClass.FieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFvIsMutable();
          fv_.add(value);
          onChanged();
        } else {
          fvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder addFv(
          int index, ClientRespondOuterClass.FieldValue value) {
        if (fvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFvIsMutable();
          fv_.add(index, value);
          onChanged();
        } else {
          fvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder addFv(
          ClientRespondOuterClass.FieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.add(builderForValue.build());
          onChanged();
        } else {
          fvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder addFv(
          int index, ClientRespondOuterClass.FieldValue.Builder builderForValue) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.add(index, builderForValue.build());
          onChanged();
        } else {
          fvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder addAllFv(
          java.lang.Iterable<? extends ClientRespondOuterClass.FieldValue> values) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fv_);
          onChanged();
        } else {
          fvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder clearFv() {
        if (fvBuilder_ == null) {
          fv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public Builder removeFv(int index) {
        if (fvBuilder_ == null) {
          ensureFvIsMutable();
          fv_.remove(index);
          onChanged();
        } else {
          fvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public ClientRespondOuterClass.FieldValue.Builder getFvBuilder(
          int index) {
        return getFvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public ClientRespondOuterClass.FieldValueOrBuilder getFvOrBuilder(
          int index) {
        if (fvBuilder_ == null) {
          return fv_.get(index);  } else {
          return fvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public java.util.List<? extends ClientRespondOuterClass.FieldValueOrBuilder> 
           getFvOrBuilderList() {
        if (fvBuilder_ != null) {
          return fvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fv_);
        }
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public ClientRespondOuterClass.FieldValue.Builder addFvBuilder() {
        return getFvFieldBuilder().addBuilder(
            ClientRespondOuterClass.FieldValue.getDefaultInstance());
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public ClientRespondOuterClass.FieldValue.Builder addFvBuilder(
          int index) {
        return getFvFieldBuilder().addBuilder(
            index, ClientRespondOuterClass.FieldValue.getDefaultInstance());
      }
      /**
       * <code>repeated .FieldValue fv = 1;</code>
       */
      public java.util.List<ClientRespondOuterClass.FieldValue.Builder> 
           getFvBuilderList() {
        return getFvFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ClientRespondOuterClass.FieldValue, ClientRespondOuterClass.FieldValue.Builder, ClientRespondOuterClass.FieldValueOrBuilder> 
          getFvFieldBuilder() {
        if (fvBuilder_ == null) {
          fvBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ClientRespondOuterClass.FieldValue, ClientRespondOuterClass.FieldValue.Builder, ClientRespondOuterClass.FieldValueOrBuilder>(
                  fv_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          fv_ = null;
        }
        return fvBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MapFieldValue)
    }

    static {
      defaultInstance = new MapFieldValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MapFieldValue)
  }

  public interface FieldValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FieldValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string field = 1;</code>
     */
    boolean hasField();
    /**
     * <code>required string field = 1;</code>
     */
    java.lang.String getField();
    /**
     * <code>required string field = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldBytes();

    /**
     * <code>required bytes value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code FieldValue}
   */
  public static final class FieldValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FieldValue)
      FieldValueOrBuilder {
    // Use FieldValue.newBuilder() to construct.
    private FieldValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FieldValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FieldValue defaultInstance;
    public static FieldValue getDefaultInstance() {
      return defaultInstance;
    }

    public FieldValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FieldValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              field_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientRespondOuterClass.internal_static_FieldValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientRespondOuterClass.internal_static_FieldValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRespondOuterClass.FieldValue.class, ClientRespondOuterClass.FieldValue.Builder.class);
    }

    public static com.google.protobuf.Parser<FieldValue> PARSER =
        new com.google.protobuf.AbstractParser<FieldValue>() {
      public FieldValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FieldValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FieldValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIELD_FIELD_NUMBER = 1;
    private java.lang.Object field_;
    /**
     * <code>required string field = 1;</code>
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string field = 1;</code>
     */
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          field_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      field_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasField()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFieldBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFieldBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientRespondOuterClass.FieldValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientRespondOuterClass.FieldValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientRespondOuterClass.FieldValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRespondOuterClass.FieldValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientRespondOuterClass.FieldValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FieldValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FieldValue)
        ClientRespondOuterClass.FieldValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientRespondOuterClass.internal_static_FieldValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientRespondOuterClass.internal_static_FieldValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRespondOuterClass.FieldValue.class, ClientRespondOuterClass.FieldValue.Builder.class);
      }

      // Construct using ClientRespondOuterClass.FieldValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        field_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientRespondOuterClass.internal_static_FieldValue_descriptor;
      }

      public ClientRespondOuterClass.FieldValue getDefaultInstanceForType() {
        return ClientRespondOuterClass.FieldValue.getDefaultInstance();
      }

      public ClientRespondOuterClass.FieldValue build() {
        ClientRespondOuterClass.FieldValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientRespondOuterClass.FieldValue buildPartial() {
        ClientRespondOuterClass.FieldValue result = new ClientRespondOuterClass.FieldValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.field_ = field_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientRespondOuterClass.FieldValue) {
          return mergeFrom((ClientRespondOuterClass.FieldValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientRespondOuterClass.FieldValue other) {
        if (other == ClientRespondOuterClass.FieldValue.getDefaultInstance()) return this;
        if (other.hasField()) {
          bitField0_ |= 0x00000001;
          field_ = other.field_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasField()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientRespondOuterClass.FieldValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientRespondOuterClass.FieldValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object field_ = "";
      /**
       * <code>required string field = 1;</code>
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string field = 1;</code>
       */
      public java.lang.String getField() {
        java.lang.Object ref = field_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            field_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        java.lang.Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string field = 1;</code>
       */
      public Builder setField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string field = 1;</code>
       */
      public Builder clearField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <code>required string field = 1;</code>
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FieldValue)
    }

    static {
      defaultInstance = new FieldValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FieldValue)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRespond_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientRespond_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapFieldValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MapFieldValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FieldValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientRespond.proto\"r\n\rClientRespond\022\n" +
      "\n\002id\030\001 \002(\t\022\014\n\004type\030\002 \002(\t\022\016\n\006status\030\003 \002(\t" +
      "\022\032\n\002fv\030\004 \001(\0132\016.MapFieldValue\022\033\n\003Vfv\030\005 \003(" +
      "\0132\016.MapFieldValue\"(\n\rMapFieldValue\022\027\n\002fv" +
      "\030\001 \003(\0132\013.FieldValue\"*\n\nFieldValue\022\r\n\005fie" +
      "ld\030\001 \002(\t\022\r\n\005value\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientRespond_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientRespond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientRespond_descriptor,
        new java.lang.String[] { "Id", "Type", "Status", "Fv", "Vfv", });
    internal_static_MapFieldValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MapFieldValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MapFieldValue_descriptor,
        new java.lang.String[] { "Fv", });
    internal_static_FieldValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FieldValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FieldValue_descriptor,
        new java.lang.String[] { "Field", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
